"""The series arm still reads the engine's telemetry after engine 0.8.0.

fathom drives the multi-PR engine as a scored arm and holds its own copy of the
engine-agnostic contract (``docs/specs/2026-07-03-series-engine-contract.md``). That
makes an additive engine release a contract-sync event for THIS repo: both backlogs
warned about exactly this case, and the engine's own changelog marks the affected
entries **(consumer-affecting)**.

Engine 0.8.0 added, all additively:

* a ``spawn_start`` event (the in-flight marker, no economy),
* a ``run_abandoned`` terminal event, and ``abandoned`` joining the reconstructed
  outcome vocabulary,
* ``effort``, ``budget_cap_usd``, ``budget_nearing``, ``classification`` and
  ``output_tail`` on ``spawn_complete``,
* ``spec_path`` / ``spec_sha256`` on ``run_start``,
* ``dead`` as a run *state* (a status-command concept — never on this wire).

The fixtures under ``tests/fixtures/`` were generated by the engine's OWN
``convoy.core.telemetry`` dataclasses and ``to_json_line`` at version 0.8.0, so they
cannot drift from the real writer by transcription error; regenerate them from the
engine rather than editing them by hand. The core stays stdlib-only: this test reads
committed JSONL and never imports the engine.

Stdlib-only: ``python tests/test_series_contract_convoy_080.py`` runs without uv.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from fathom.strategies.base import TrialStatus  # noqa: E402
from fathom.strategies.series import (  # noqa: E402
    EngineOutcome,
    _classify,
    _final_run_outcome,
    _materialize_runs,
    _read_events,
    _select_run_id,
)

FIXTURES = Path(__file__).parent / "fixtures"
COMPLETED = FIXTURES / "convoy-0.8.0-spawns.jsonl"
ABANDONED = FIXTURES / "convoy-0.8.0-spawns-abandoned.jsonl"


def _ok(returncode: int = 0) -> EngineOutcome:
    return EngineOutcome(
        returncode=returncode, stdout="", stderr="", duration_s=1.0, timed_out=False
    )


class ContractParsesEngine080(unittest.TestCase):
    def setUp(self) -> None:
        self.events = _read_events(COMPLETED)
        self.run_id = _select_run_id(self.events, set())

    def test_every_line_parses(self) -> None:
        """A malformed line would be warned-and-skipped, which would hide a break."""
        self.assertEqual(len(self.events), 9)
        self.assertEqual(
            [e["event"] for e in self.events],
            [
                "run_start",
                "spawn_start",
                "spawn_complete",
                "gate_complete",
                "spawn_start",
                "spawn_complete",
                "gate_complete",
                "pr_skipped",
                "run_complete",
            ],
        )

    def test_run_id_selection_survives_the_new_events(self) -> None:
        self.assertEqual(self.run_id, "20260811T090000Z-ab12")

    def test_only_spawn_complete_becomes_economy(self) -> None:
        """``spawn_start`` carries no economy; counting it would double every arm."""
        runs = _materialize_runs(self.events, self.run_id)
        self.assertEqual(len(runs), 2)
        self.assertEqual([r.num_turns for r in runs], [18, 7])
        self.assertEqual([r.tokens_in for r in runs], [12000, 9000])
        self.assertEqual([r.tokens_out for r in runs], [3400, 1500])
        self.assertAlmostEqual(sum(r.cost_usd_est for r in runs), 1.7445, places=4)
        self.assertEqual([r.model_id for r in runs], ["claude-haiku-4-5"] * 2)

    def test_new_spawn_complete_fields_survive_into_usage(self) -> None:
        """Additive fields must reach a consumer, not be silently dropped."""
        runs = _materialize_runs(self.events, self.run_id)
        fix = runs[1].usage
        self.assertEqual(fix["effort"], "high")
        self.assertEqual(fix["budget_cap_usd"], 1.0)
        self.assertTrue(fix["budget_nearing"])
        self.assertEqual(fix["classification"], "ok")
        self.assertTrue(fix["cost_estimated"])

    def test_terminal_outcome_and_classification(self) -> None:
        self.assertEqual(_final_run_outcome(self.events), "completed")
        status, detail = _classify(_ok(), self.events)
        self.assertEqual(status, TrialStatus.COMPLETED)
        self.assertEqual(detail, "")


class AbandonedIsInfrastructure(unittest.TestCase):
    """0.8.0's second terminal line must not fall through to a task verdict.

    Before this was mapped, a stream terminated by ``run_abandoned`` produced
    ``_final_run_outcome() is None``, so the trial was judged on the engine's exit
    code alone — and a run whose driver was killed can exit 0 from the wrapper that
    outlived it, which would have scored an abandoned run as a COMPLETED task.
    """

    def setUp(self) -> None:
        self.events = _read_events(ABANDONED)

    def test_outcome_is_abandoned(self) -> None:
        self.assertEqual(_final_run_outcome(self.events), "abandoned")

    def test_classified_infrastructure_not_completed(self) -> None:
        status, detail = _classify(_ok(returncode=0), self.events)
        self.assertEqual(status, TrialStatus.INFRASTRUCTURE)
        self.assertIn("infrastructure", detail)

    def test_started_spawn_with_no_completion_yields_no_economy(self) -> None:
        run_id = _select_run_id(self.events, set())
        self.assertEqual(_materialize_runs(self.events, run_id), [])


if __name__ == "__main__":
    unittest.main()
